/**
 * Created by seal on 21/01/2017.
 */

export const UPDATE_PROJECTS = 'UPDATE_PROJECTS'
export const UPDATE_ARTICLES =  'UPDATE_ARTICLES'
export const UPDATE_RECORDS_CACHE =  'UPDATE_RECORDS_CACHE'
export const UPDATE_NUM = 'UPDATE_NUM'
export const UPDATE_USERS = 'UPDATE_USERS'
export const UPDATE_OUT_RECORDS = 'UPDATE_OUT_RECORDS'
export const REQUEST_OUT_RECORDS = 'REQUEST_OUT_RECORDS'
export const UPDATE_IN_RECORDS =  'UPDATE_IN_RECORDS'
export const REQUEST_IN_RECORDS =  'REQUEST_IN_RECORDS'
